Class {
	#name : 'FamixTagTestEntity',
	#superclass : 'MooseEntity',
	#category : 'Famix-Tagging-Tests-Entities-Entities',
	#package : 'Famix-Tagging-Tests-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTagTestEntity class >> annotation [

	<ignoreForCoverage>
	<FMClass: #Entity super: #MooseEntity>
	<package: #'Famix-Tagging-Tests-Entities'>
	<generated>
	<abstract>
]

{ #category : 'testing' }
FamixTagTestEntity class >> isAbstract [

	<ignoreForCoverage>
	<generated>
	^ self == FamixTagTestEntity
]

{ #category : 'meta' }
FamixTagTestEntity class >> metamodel [

	<ignoreForCoverage>
	<generated>
	^ FamixTagTestModel metamodel
]

{ #category : 'testing' }
FamixTagTestEntity >> canBeStub [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTagTestEntity >> hasImmediateSource [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTagTestEntity >> isAccess [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTagTestEntity >> isAssociation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTagTestEntity >> isAttribute [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTagTestEntity >> isBehavioural [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTagTestEntity >> isClass [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTagTestEntity >> isInvocation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTagTestEntity >> isMethod [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTagTestEntity >> isPackage [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTagTestEntity >> isQueryable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTagTestEntity >> isStructuralEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTagTestEntity >> isType [

	<ignoreForCoverage>
	<generated>
	^ false
]
