Class {
	#name : #FamixTagTestSourceTextAnchor,
	#superclass : #FamixTagTestEntity,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Famix-Tagging-Tests-Entities-Entities'
}

{ #category : #meta }
FamixTagTestSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixTagTestEntity>
	<package: #'Famix-Tagging-Tests-Entities'>
	<generated>
	^ self
]
