Class {
	#name : 'FamixTagTestAttribute',
	#superclass : 'FamixTagTestEntity',
	#traits : 'FamixTAttribute',
	#classTraits : 'FamixTAttribute classTrait',
	#category : 'Famix-Tagging-Tests-Entities-Entities',
	#package : 'Famix-Tagging-Tests-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTagTestAttribute class >> annotation [

	<FMClass: #Attribute super: #FamixTagTestEntity>
	<package: #'Famix-Tagging-Tests-Entities'>
	<generated>
	^ self
]
